language: php
php:
  - 5.6
  - 7.0
env: # important!
matrix:
  fast_finish: true
  include:
    - php: 5.6
      env: 
    - php: 7.0
      env: 
  allow_failures:
    - php: 7.0
	
script: phpunit --group popnikos --log-junit $TMP/popnikos_results.xml
