language: php

php:
  - 5.6
  - 7.0

env: # important!

matrix:
  fast_finish: true
  allow_failures:
    - php: 7.0
    - php: 7.1
    
before_script:
  - composer install --dev

script: phpunit --group popnikos
